<!DOCTYPE html>
<html>
    <head>
        <title>Request</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        
        <?php if(!empty($data)):?>
          <table border="1" cellspacing="0">
            <?php foreach($data as $key => $value): ?>
              <tr>
                  <td><?=$key?></td>
                  <td>
                      <?php if(is_array($value)):?>
                      <ul>
                        <?php foreach($value as $vkey => $vvalue): ?>
                            <li>
                                <?php if(is_array($vvalue)):?>
                                <ul>
                                    <?php foreach($vvalue as $k => $v):?>
                                    <li>
                                        <?=$v ?>
                                    </li>
                                    <?php endforeach;?>
                                </ul>
                                <?php else:?> 
                                <?=$vvalue?>
                                <?php endif;?>
                            </li>
                        <?php endforeach;?>
                      </ul>
                      <?php else: ?>
                        <?=$value?>
                      <?php endif; ?>
                  </td>
              </tr>
            <?php endforeach;?>
            </table>
        <?php endif; ?>
    </body>
</html>
